# Generated by Django 5.0 on 2023-12-16 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='TgToken',
        ),
        migrations.DeleteModel(
            name='TgUser',
        ),
        migrations.RemoveField(
            model_name='mysession',
            name='session_data',
        ),
        migrations.AddField(
            model_name='mysession',
            name='tg_token',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mysession',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
